apiVersion: v1
kind: Service
metadata:
  name: service-owl-fe
  labels:
    name: service-owl-fe
spec:
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
      nodePort: 30080
  externalIPs:
    - 192.168.130.70
  selector:
    app: so-fe
  type: NodePort
